nginx:
    container_name: nginx
    build: ./nginx/
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - app

php:
    container_name: php
    build: ./php/
    links:
        - mysql
    expose:
        - 9000
    volumes_from:
        - app

app:
    image: php:7.0-fpm
    volumes:
        - ..:/var/www/html
    command: "true"

mysql:
    container_name: mysql
    image: mysql:latest
    volumes_from:
        - data
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: project
        MYSQL_USER: project
        MYSQL_PASSWORD: project

data:
    image: mysql:latest
    volumes:
        - ./database:/var/lib/mysql
        - ../sql:/home/sql
    command: "true"


